# fly.toml app configuration file generated for plivo-ask-me on 2023-04-27T22:40:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "plivo-ask-me"
primary_region = "iad"

[http_service]
  internal_port = 50505
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
