# fly.toml app configuration file generated for plivo-ask-me on 2023-04-27T22:40:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "plivo-ask-me"
primary_region = "iad"

[http_service]
  internal_port = 50505
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[checks]
  [checks.alive]
    grace_period = "10s"
    interval = "10s"
    method = "get"
    path = "/status"
    port = 50505
    timeout = "5s"
    type = "http"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    ARCH="amd64"

[env]
  OPENAI_MODEL="gpt-4"
  VECTOR_DATABASE="qdrant://https://7b453944-1c59-4473-8fbd-ebe30cf3cd42.us-east-1-0.aws.cloud.qdrant.io:6333"
  ENV="prod"
  ARCH="amd64"
  OPENAI_REQUEST_TIMEOUT="180"

[mounts]
 source="plivo_askme_data"
 destination="/data"

