# fly.toml app configuration file generated for plivo-ask-me2 on 2023-05-04T16:21:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "plivo-ask-me2"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    ARCH = "amd64"

[env]
  ARCH = "amd64"
  ENV = "prod"
  OPENAI_MODEL = "gpt-4"
  OPENAI_REQUEST_TIMEOUT = "180"
  VECTOR_DATABASE = "qdrant://http://e2865649c30758.vm.plivo-ask-me2.internal:6333"

[processes]
  slackbot = "/bin/bash -c ./start_slackbot.sh"
  qdrant = "/bin/bash -c ./start_qdrant.sh"
  ingest = "/bin/bash -c './start_ingest.sh flymode'"

[[mounts]]
  source = "plivo_askme2_data"
  destination = "/data"
  processes = ["qdrant"]

[[services]]
  protocol = "tcp"
  internal_port = 50505
  auto_start_machines = true
  auto_stop_machines = false
  processes = ["slackbot"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.alive_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 2
    method = "get"
    path = "/status"
    protocol = "http"

[[services]]
  protocol = "tcp"
  internal_port = 6333
  auto_start_machines = true
  auto_stop_machines = false
  processes = ["qdrant"]

  [[services.alive_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 2
    method = "get"
    path = "/"
    protocol = "http"

#[[services]]
#  auto_start_machines = false
#  auto_stop_machines = false
#  processes = ["ingest"]

