version: "3"
services:
  bot:
    image: test/bot
    networks:
      - bot-vpc
    volumes:
      - ${PWD}:/app
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - bot-vpc
    volumes:
      - ${PWD}/data:/data
networks:
  bot-vpc: {}
